"""initial_schema

Revision ID: f3f36de0e628
Revises: 
Create Date: 2026-09-25 05:17:22.595581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f36de0e628'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active_bundle_id', sa.String(length=64), nullable=True),
    sa.Column('identity_epoch', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('source_system_id', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('classes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name')
    )
    op.create_index(op.f('ix_classes_tenant_id'), 'classes', ['tenant_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('class_name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('owner_actor_id', sa.String(length=128), nullable=True),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('redirect_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id')
    )
    op.create_index(op.f('ix_entities_tenant_id'), 'entities', ['tenant_id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('class_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('sensitivity', sa.String(length=20), nullable=False),
    sa.Column('authority_source_system_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'class_name', 'name')
    )
    op.create_index(op.f('ix_properties_tenant_id'), 'properties', ['tenant_id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('applies_to', sa.String(length=128), nullable=False),
    sa.Column('expression', sa.JSON(), nullable=False),
    sa.Column('required_facts', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', 'version')
    )
    op.create_index(op.f('ix_rules_tenant_id'), 'rules', ['tenant_id'], unique=False)
    op.create_table('source_systems',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('max_age_seconds', sa.Integer(), nullable=False),
    sa.Column('complete_until', sa.DateTime(), nullable=True),
    sa.Column('last_successful_sync_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name')
    )
    op.create_index(op.f('ix_source_systems_tenant_id'), 'source_systems', ['tenant_id'], unique=False)
    op.create_table('mappings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('source_system_id', sa.String(length=64), nullable=False),
    sa.Column('target_class', sa.String(length=128), nullable=False),
    sa.Column('field_map', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_system_id', 'version')
    )
    op.create_index(op.f('ix_mappings_tenant_id'), 'mappings', ['tenant_id'], unique=False)
    op.create_table('semantic_bundles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('mapping_versions', sa.JSON(), nullable=False),
    sa.Column('identity_epoch', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_bundles_tenant_id'), 'semantic_bundles', ['tenant_id'], unique=False)
    op.create_table('source_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('source_system_id', sa.String(length=64), nullable=False),
    sa.Column('record_key', sa.String(length=256), nullable=False),
    sa.Column('locator', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_system_id', 'record_key')
    )
    op.create_index(op.f('ix_source_records_source_system_id'), 'source_records', ['source_system_id'], unique=False)
    op.create_index(op.f('ix_source_records_tenant_id'), 'source_records', ['tenant_id'], unique=False)
    op.create_table('sync_tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('source_system_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_tasks_state'), 'sync_tasks', ['state'], unique=False)
    op.create_index(op.f('ix_sync_tasks_tenant_id'), 'sync_tasks', ['tenant_id'], unique=False)
    op.create_table('assertion_revisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=64), nullable=False),
    sa.Column('source_system_id', sa.String(length=64), nullable=False),
    sa.Column('predicate', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('source_version', sa.Integer(), nullable=False),
    sa.Column('mapping_version', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_record_id', 'source_version', 'mapping_version', 'predicate')
    )
    op.create_index('ix_assertion_entity_predicate', 'assertion_revisions', ['tenant_id', 'entity_id', 'predicate'], unique=False)
    op.create_index(op.f('ix_assertion_revisions_tenant_id'), 'assertion_revisions', ['tenant_id'], unique=False)
    op.create_table('identity_bindings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('reviewer_id', sa.String(length=128), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_record_id')
    )
    op.create_index(op.f('ix_identity_bindings_entity_id'), 'identity_bindings', ['entity_id'], unique=False)
    op.create_index(op.f('ix_identity_bindings_tenant_id'), 'identity_bindings', ['tenant_id'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('requester_id', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('bundle_id', sa.String(length=64), nullable=False),
    sa.Column('identity_epoch', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('execution_state', sa.String(length=20), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('quality', sa.JSON(), nullable=False),
    sa.Column('rule_trace', sa.JSON(), nullable=False),
    sa.Column('source_reads', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['semantic_bundles.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'requester_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_investigations_tenant_id'), 'investigations', ['tenant_id'], unique=False)
    op.create_table('sync_checkpoints',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=64), nullable=False),
    sa.Column('last_version', sa.Integer(), nullable=False),
    sa.Column('last_payload_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_record_id')
    )
    op.create_index(op.f('ix_sync_checkpoints_tenant_id'), 'sync_checkpoints', ['tenant_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('assertion_id', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('predicate', sa.String(length=128), nullable=False),
    sa.Column('observed_value', sa.JSON(), nullable=True),
    sa.Column('source_record_id', sa.String(length=64), nullable=False),
    sa.Column('source_version', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assertion_id'], ['assertion_revisions.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_investigation_id'), 'evidence', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_evidence_tenant_id'), 'evidence', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_tenant_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_investigation_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_sync_checkpoints_tenant_id'), table_name='sync_checkpoints')
    op.drop_table('sync_checkpoints')
    op.drop_index(op.f('ix_investigations_tenant_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_identity_bindings_tenant_id'), table_name='identity_bindings')
    op.drop_index(op.f('ix_identity_bindings_entity_id'), table_name='identity_bindings')
    op.drop_table('identity_bindings')
    op.drop_index(op.f('ix_assertion_revisions_tenant_id'), table_name='assertion_revisions')
    op.drop_index('ix_assertion_entity_predicate', table_name='assertion_revisions')
    op.drop_table('assertion_revisions')
    op.drop_index(op.f('ix_sync_tasks_tenant_id'), table_name='sync_tasks')
    op.drop_index(op.f('ix_sync_tasks_state'), table_name='sync_tasks')
    op.drop_table('sync_tasks')
    op.drop_index(op.f('ix_source_records_tenant_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_source_system_id'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_index(op.f('ix_semantic_bundles_tenant_id'), table_name='semantic_bundles')
    op.drop_table('semantic_bundles')
    op.drop_index(op.f('ix_mappings_tenant_id'), table_name='mappings')
    op.drop_table('mappings')
    op.drop_index(op.f('ix_source_systems_tenant_id'), table_name='source_systems')
    op.drop_table('source_systems')
    op.drop_index(op.f('ix_rules_tenant_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_properties_tenant_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_entities_tenant_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_classes_tenant_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('tenants')
    # ### end Alembic commands ###
